### PR TITLE
Fixing CI

### LINKED ISSUE #681: Travis tests are failing on JRuby

### PR DESCRIPTION
**Pull request by pitr-ch**
fix #681

### CODE REVIEW

File: lib/concurrent/atomic/count_down_latch.rb [hunk 1]
```diff
@@ -55,7 +55,7 @@ module Concurrent
   # @!macro internal_implementation_note
   CountDownLatchImplementation = case
                                  when Concurrent.on_jruby?
-                                   JavaCountDownLatch
```
Comment (kares) [inline lib/concurrent/atomic/count_down_latch.rb]: hey, could we get some details on why the 'native' JRuby stuff, seems to be going away?
understand the limited time for maintenance but still seems weird these had to go ...

Comment (pitr-ch) [reply lib/concurrent/atomic/count_down_latch.rb]: Sure, please have a look at #717. I am updating the changelog before release, and when the 1.0.6.pre goes out it will mention this as well.

Comment (pitr-ch) [reply lib/concurrent/atomic/count_down_latch.rb]: Please ask any follow up questions there.
