### PR TITLE
Fix Future#flat when failures happen

### LINKED ISSUE #426: Inconsistent `flat` behavior
Using concurrent-ruby-edge 0.2.0pre2 on jRuby 9.0.1.0.

The FlatPromise only resolves if the contained future is successful. If the inner future fails, or raises, then the flat never resolves and hangs the program if you `wait` or call `value`.

```ruby
# Works
foo = Concurrent.future { Concurrent.future { 7 } }.flat
foo.value! # 7

# Fails
bar = Concurrent.future { Concurrent.future { raise "no" } }.flat
bar.value! # Hangs

# OR

baz = Concurrent.future { Concurrent.failed_future("no") }.flat
baz.value! # Hangs
```

### PR DESCRIPTION
**Pull request by pitr-ch**
fix #426

### CODE REVIEW

File: spec/concurrent/edge/future_spec.rb [hunk 1]
```diff
@@ -312,6 +312,16 @@
     it 'has flat map' do
       f = Concurrent.future { Concurrent.future { 1 } }.flat.then(&:succ)
       expect(f.value!).to eq 2
+
+      err = StandardError.new('boo')
+      f   = Concurrent.future { Concurrent.failed_future(err) }.flat
+      expect(f.reason).to eq err
+
+      f   = Concurrent.future { raise 'boo' }.flat
```
Comment (hobodave) [inline spec/concurrent/edge/future_spec.rb]: I think this should be `Concurrent.future { Concurrent.future { raise 'boo' } }.flat` since `#flat` is expecting to be returned a future. (Or add this case as an additional test)

**Comment by hobodave** [comment]
Thanks for this @pitr-ch! I'm testing it now in our real-world use case.

**Comment by pitr-ch** [comment]
@hobodave great! Btw since this is an edge feature we are looking for a feedback about the API before it finalises and goes to concurrent core. If you have any suggestions, insights, please share.

File: spec/concurrent/edge/future_spec.rb (hunk 1 above)
Comment (pitr-ch) [inline spec/concurrent/edge/future_spec.rb]: yeah it should be a separate example, I was lazy.

**Comment by hobodave** [comment]
What would be the best mechanism to share API feedback? Creating issues?

**Comment by pitr-ch** [comment]
@hobodave yeah please create an issue.

**Comment by jdantonio** [comment]
@pitr-ch Will you be merging this today? I'd like to publish the next pre-release today.

**Comment by pitr-ch** [comment]
@jdantonio just waiting for @hobodave to confirm that it fixes the issues for him, after that it can be merged.

**Comment by hobodave** [comment]
Confirmed :+1:
