### PR TITLE
Fix Intermittently Failing Tests

### LINKED ISSUE #117: Intermittently Failing Tests
I'm still trying to address all the intermittently failing tests. It's a [Sisyphean](http://en.wikipedia.org/wiki/Sysiphus) task. Please use this thread to link to any failing Travis test runs that you believe are due to buggy tests.

### PR DESCRIPTION
**Pull request by jdantonio**
Addresses #117 and #263

### CODE REVIEW

File: lib/concurrent/utility/monotonic_time.rb [hunk 1]
```diff
@@ -55,6 +55,22 @@ def monotonic_time
...
+  #
+  # @raise [ArgumentError] when no block given
+  #
+  # @!macro monotonic_clock_warning
+  def monotonic_interval
+    raise ArgumentError.new('no block given') unless block_given?
+    start_time = GLOBAL_MONOTONIC_CLOCK.get_time
+    yield
+    GLOBAL_MONOTONIC_CLOCK.get_time - start_time
+  end
```
Comment (pitr-ch) [inline lib/concurrent/utility/monotonic_time.rb]: This method may not return correct results on MRI if there was time shift, it may be better kept just in test helper.

File: spec/concurrent/atomic/condition_spec.rb [hunk 2]
```diff
@@ -32,37 +27,80 @@ module Concurrent
...
+            t = Thread.new do
+              mutex.synchronize do
+                latch_1.count_down
+                subject.wait(mutex)
+                latch_2.count_down
+              end
+            end
+
+            latch_1.wait(1)
+            latch_2.wait(0.1)
```
Comment (pitr-ch) [inline spec/concurrent/atomic/condition_spec.rb]: It might be better practice to use Events in similar cases giving the variable some name for improved readability. 
```ruby
  before_waiting = Concurrent::Event.new
  after_waiting = Concurrent::Event.new
  mutex = Mutex.new

  thread = Thread.new do
    mutex.synchronize do
      before_waiting.set
      subject.wait(mutex)
      after_waiting.set
    end
  end

  before_waiting.wait(1)
  after_waiting.wait(0.1)
  expect(after_waiting.set?).to be_false
  thread.kill
```
But both latch and event cannot be used here because both depend on the `Condition` which is being testes here. `Queue` may be good replacement here.
