### PR TITLE
Fix race condition in TVar for stale reads, fixes #885

### LINKED ISSUE #885: Race condition in TVar
When a `TVar` is first written to, the fact that it's been locked isn't recorded until *after* the check if any previous reads are now stale. If the transaction aborts at this point due to stale reads the `TVar` is left locked.

### PR DESCRIPTION
**Pull request by chrisseaton**

### CODE REVIEW

**Comment by headius** [comment]
You've got a rogue `puts` in there...

File: lib/concurrent-ruby/concurrent/tvar.rb [hunk 1]
```diff
@@ -224,6 +227,7 @@ def commit
 
       unlock
 
+      puts 'committed'
```
Comment (headius) [inline lib/concurrent-ruby/concurrent/tvar.rb:230]: Remove. 😀

**Review by headius — CHANGES_REQUESTED** [review]

**Review by headius — APPROVED** [review]
