### PR TITLE
Fixes format-security error when compiling ruby_193_compatible.h

### LINKED ISSUE #516: An error occurred while installing concurrent-ruby-ext (0.9.0)
Hey guys! I have an 'old' project using `ruby 1.9.3-p448` installed using rbenv and `concurrent-ruby-ext 0.9.0`. Today I was trying to install my gems using `bundle install` on a new computer (ubuntu 14.04) and only `concurrent-ruby-ext` gem failed to build.

In my Gemfile I have:
```
...
gem 'rails', '= 3.2.21'
gem 'concurrent-ruby-ext', '~> 0.9.0', require: 'concurrent'
...
```

The error I got is:
```
Installing concurrent-ruby-ext 0.9.0 with native extensions

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
checking for libkern/OSAtomic.h... no
creating Makefile

make
compiling rb_concurrent.c
compiling atomic_reference.c
compiling atomic_fixnum.c
In file included from atomic_fixnum.c:5:0:
ruby_193_compatible.h: In function ‘rb_error_arity’:
ruby_193_compatible.h:20:3: warning: passing argument 2 of ‘rb_raise’ makes pointer from integer without a cast [enabled by default]
   rb_raise(rb_eTypeError, err_mess);
   ^
In file included from /usr/include/ruby-1.9.1/ruby.h:32:0,
                 from atomic_fixnum.c:1:
/usr/include/ruby-1.9.1/ruby/ruby.h:1172:27: note: expected ‘const char *’ but argument is of type ‘VALUE’
 PRINTF_ARGS(NORETURN(void rb_raise(VALUE, const char*, ...)), 2, 3);
                           ^
/usr/include/ruby-1.9.1/ruby/ruby.h:42:3: note: in definition of macro ‘PRINTF_ARGS’
   decl __attribute__((format(printf, string_index, first_to_check)))
   ^
/usr/include/ruby-1.9.1/ruby/ruby.h:1172:13: note: in expansion of macro ‘NORETURN’
 PRINTF_ARGS(NORETURN(void rb_raise(VALUE, const char*, ...)), 2, 3);
             ^
In file included from atomic_fixnum.c:5:0:
ruby_193_compatible.h:20:3: error: format not a string literal and no format arguments [-Werror=format-security]
   rb_raise(rb_eTypeError, err_mess);
   ^
cc1: some warnings being treated as errors
make: *** [atomic_fixnum.o] Error 1


Gem files will remain installed in /tmp/bundler20160226-18427-13v8kyrconcurrent-ruby-ext-0.9.0/gems/concurrent-ruby-ext-0.9.0 for inspection.
Results logged to /tmp/bundler20160226-18427-13v8kyrconcurrent-ruby-ext-0.9.0/gems/concurrent-ruby-ext-0.9.0/ext/concurrent/gem_make.out
```

Am I missing something? Using my work computer I can `bundle install` without any problem...

### PR DESCRIPTION
**Pull request by RJPercival**
Fixes #516. When compiling the extension for Ruby 1.9 on a system that treats format-security warnings as errors (i.e. the Makefile generated for the extension contains "-Werror=format-security"), compilation would fail with the following error:

```
compiling atomic_boolean.c
In file included from atomic_boolean.c:5:0:
ruby_193_compatible.h: In function 'rb_error_arity':
ruby_193_compatible.h:20:3: warning: passing argument 2 of 'rb_raise' makes pointer from integer without a cast [enabled by
 default]
   rb_raise(rb_eTypeError, err_mess);
   ^
In file included from /usr/include/ruby-1.9.1/ruby.h:32:0,
                 from atomic_boolean.c:1:
/usr/include/ruby-1.9.1/ruby/ruby.h:1172:27: note: expected 'const char *' but argument is of type 'VALUE'
 PRINTF_ARGS(NORETURN(void rb_raise(VALUE, const char*, ...)), 2, 3);
#ifndef rb_check_arity
                           ^
/usr/include/ruby-1.9.1/ruby/ruby.h:42:3: note: in definition of macro 'PRINTF_ARGS'
   decl __attribute__((format(printf, string_index, first_to_check)))
   ^
/usr/include/ruby-1.9.1/ruby/ruby.h:1172:13: note: in expansion of macro 'NORETURN'
 PRINTF_ARGS(NORETURN(void rb_raise(VALUE, const char*, ...)), 2, 3);
             ^
In file included from atomic_boolean.c:5:0:
ruby_193_compatible.h:20:3: error: format not a string literal and no format arguments [-Werror=format-security]
   rb_raise(rb_eTypeError, err_mess);
   ^
cc1: some warnings being treated as errors
make: *** [atomic_boolean.o] Error 1
```

This updates the functions in ruby_193_compatible.h to work more like the original copies (found in the Ruby 2.0+ source code), which avoids this compilation error.

### CODE REVIEW

File: ext/concurrent/ruby_193_compatible.h [hunk 1]
```diff
@@ -17,12 +17,12 @@ static inline void rb_error_arity(int argc, int min, int max)
   else {
     err_mess = rb_sprintf("wrong number of arguments (%d for %d..%d)", argc, min, max);
   }
-  rb_raise(rb_eTypeError, err_mess);
+  return rb_ext_new3(rb_eTypeError, err_mess);
```
Comment (ianks) [inline ext/concurrent/ruby_193_compatible.h]: Where did you find the documentation on `rb_ext_new3`?

Comment (RJPercival) [inline ext/concurrent/ruby_193_compatible.h]: Oops, that's supposed to be `rb_exc_new3` - fixed.

Comment (RJPercival) [inline ext/concurrent/ruby_193_compatible.h]: I'm surprised the Travis build succeeded. It looks like the extension is being compiled with very lenient settings, to the extent that calling non-existent functions isn't even considered an error!

**Comment by pitr-ch** [comment]
@RJPercival Thanks very much for the fix.

**Comment by jdantonio** [comment]
Thank you!
